# Generated by Django 4.2.21 on 2026-04-01 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0002_alter_embarcaciones_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Concepto de Cobro',
                'verbose_name_plural': 'Conceptos de Cobro',
            },
        ),
        migrations.CreateModel(
            name='CuentaCorriente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cuenta', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('FAMILIAR', 'Familiar')], max_length=20)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('CERRADA', 'Cerrada')], default='ACTIVA', max_length=20)),
                ('fecha_apertura', models.DateField(auto_now_add=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('socio_titular', models.OneToOneField(help_text='Una cuenta corriente por titular.', on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_corriente', to='usuarios.socios')),
            ],
            options={
                'verbose_name': 'Cuenta Corriente',
                'verbose_name_plural': 'Cuentas Corrientes',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medio_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TRANSFERENCIA', 'Transferencia'), ('BROU', 'BROU'), ('OTRO', 'Otro')], max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='cobranzas.cuentacorriente')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(help_text='Formato YYYY-MM', max_length=7)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Parcialmente Pagado'), ('PAGADO', 'Pagado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cobranzas.conceptocobro')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargos', to='cobranzas.cuentacorriente')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='AplicacionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe_aplicado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aplicaciones', to='cobranzas.cargo')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='cobranzas.pago')),
            ],
            options={
                'verbose_name': 'Aplicación de Pago',
                'verbose_name_plural': 'Aplicaciones de Pagos',
            },
        ),
        migrations.AddConstraint(
            model_name='pago',
            constraint=models.CheckConstraint(check=models.Q(('importe_total__gt', 0)), name='pago_importe_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='cargo',
            constraint=models.CheckConstraint(check=models.Q(('importe__gt', 0)), name='cargo_importe_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='aplicacionpago',
            constraint=models.CheckConstraint(check=models.Q(('importe_aplicado__gt', 0)), name='aplicacion_importe_gt_0'),
        ),
    ]
