# Generated by Django 4.2.21 on 2026-04-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0002_conceptocobro_importe_por_defecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conceptocobro',
            name='importe_por_defecto',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Precio actual o base', max_digits=10, verbose_name='Importe'),
        ),
    ]
