# Generated by Django 4.2.21 on 2026-04-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0004_alter_aplicacionpago_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aplicacionpago',
            name='estado',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('REVERTIDA', 'Revertida')], default='ACTIVA', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='aplicacionpago',
            name='fecha_reversion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de reversión'),
        ),
        migrations.AddField(
            model_name='aplicacionpago',
            name='motivo_reversion',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo de reversión'),
        ),
    ]
