# Generated by Django 4.2.21 on 2026-04-09 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0005_aplicacionpago_estado_aplicacionpago_fecha_reversion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aplicacionpago',
            options={'permissions': [('puede_revertir_aplicacion_pago', 'Puede revertir aplicaciones de pago')], 'verbose_name': 'Aplicación de Pago', 'verbose_name_plural': 'Aplicaciones de Pagos'},
        ),
        migrations.AlterModelOptions(
            name='cargo',
            options={'permissions': [('puede_anular_cargo', 'Puede anular cargos generados')], 'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={'permissions': [('puede_aplicar_pago', 'Puede aplicar parcial o totalmente saldos de pago'), ('puede_ver_resumen_cobranzas', 'Puede ver resúmenes generales financieros')], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
    ]
