# Generated by Django 5.2.17 on 2026-10-02 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobranzas', '0008_proteger_movimientos_y_auditoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobantePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=32, unique=True)),
                ('datos', models.JSONField(editable=False)),
                ('reconstruido', models.BooleanField(default=False, editable=False)),
                ('emitido_en', models.DateTimeField(auto_now_add=True)),
                ('emitido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='comprobante', to='cobranzas.pago')),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='IntencionSaldoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intencion', models.CharField(choices=[('ANTICIPO', 'Anticipo intencional'), ('APLICAR', 'Pendiente de aplicación'), ('SIN_CLASIFICAR', 'Sin clasificar')], max_length=16)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='intencion_saldo', to='cobranzas.pago')),
            ],
        ),
        migrations.CreateModel(
            name='OperacionCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.UUIDField(editable=False, unique=True)),
                ('huella', models.CharField(editable=False, max_length=64)),
                ('tipo', models.CharField(choices=[('COBRO', 'Nuevo cobro'), ('APLICACION', 'Aplicación de saldo existente')], max_length=12)),
                ('intencion_anterior', models.CharField(choices=[('ANTICIPO', 'Anticipo intencional'), ('APLICAR', 'Pendiente de aplicación'), ('SIN_CLASIFICAR', 'Sin clasificar')], max_length=16)),
                ('intencion_saldo', models.CharField(choices=[('ANTICIPO', 'Anticipo intencional'), ('APLICAR', 'Pendiente de aplicación'), ('SIN_CLASIFICAR', 'Sin clasificar')], max_length=16)),
                ('aplicaciones', models.JSONField(default=list, editable=False)),
                ('saldo_final', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cobranzas.cuentacorriente')),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones', to='cobranzas.pago')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
