# Generated by Django 4.2.21 on 2025-07-27 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Embarcaciones',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.TextField()),
                ('id_socio', models.IntegerField()),
                ('marca', models.CharField(blank=True, max_length=20, null=True)),
                ('modelo', models.CharField(blank=True, max_length=20, null=True)),
                ('color', models.CharField(max_length=30)),
                ('prestamo', models.IntegerField()),
            ],
            options={
                'db_table': 'embarcaciones',
            },
        ),
        migrations.CreateModel(
            name='Historico_socios',
            fields=[
                ('fecha', models.DateField(primary_key=True, serialize=False)),
                ('familiar', models.IntegerField()),
                ('individual', models.IntegerField()),
                ('total', models.IntegerField()),
                ('personas', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historico_socios',
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_socio', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('monto', models.IntegerField()),
            ],
            options={
                'db_table': 'pagos',
            },
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('Cedula', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('numeroSocio', models.IntegerField()),
                ('PrimerNombre', models.CharField(max_length=100)),
                ('SegundoNombre', models.CharField(blank=True, max_length=100, null=True)),
                ('PrimerApellido', models.CharField(max_length=100)),
                ('SegundoApellido', models.CharField(blank=True, max_length=100, null=True)),
                ('FechaNacimiento', models.DateField(blank=True, null=True)),
                ('Edad', models.IntegerField(blank=True, null=True)),
                ('Direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('Telefono', models.CharField(blank=True, max_length=9, null=True)),
                ('Celular', models.CharField(blank=True, max_length=12, null=True)),
                ('Correo', models.CharField(blank=True, max_length=100, null=True)),
                ('relacionTitular', models.CharField(blank=True, max_length=20, null=True)),
                ('salud', models.CharField(blank=True, max_length=20, null=True)),
                ('llave', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'personas',
            },
        ),
        migrations.CreateModel(
            name='Precios',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('monto', models.IntegerField()),
                ('tipo', models.TextField()),
                ('vigente', models.IntegerField()),
                ('fecha', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'precios',
            },
        ),
        migrations.CreateModel(
            name='Recibos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('estado', models.IntegerField()),
                ('monto', models.IntegerField()),
                ('id_socio', models.CharField(max_length=8)),
                ('id_pago', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'recibos',
            },
        ),
        migrations.CreateModel(
            name='Socios',
            fields=[
                ('numero', models.IntegerField(primary_key=True, serialize=False)),
                ('activo', models.IntegerField(blank=True, null=True)),
                ('fechaAlta', models.DateField()),
                ('fechaBaja', models.DateField(blank=True, null=True)),
                ('tipo', models.TextField()),
                ('cedulaTitular', models.CharField(max_length=11)),
                ('comentarios', models.CharField(blank=True, max_length=40, null=True)),
                ('lugarPago', models.CharField(blank=True, max_length=20, null=True)),
                ('cobroEspecial', models.IntegerField(blank=True, null=True)),
                ('percha', models.IntegerField(blank=True, null=True)),
                ('Habilitado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'socios',
            },
        ),
        migrations.CreateModel(
            name='Socios_cambios',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('accion', models.TextField()),
                ('comentario', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'socios_cambios',
            },
        ),
    ]
