# Generated by Django 4.2.21 on 2026-03-31 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='embarcaciones',
            options={'verbose_name_plural': 'Embarcaciones'},
        ),
        migrations.AlterModelOptions(
            name='historico_socios',
            options={'verbose_name_plural': 'Historico Socios'},
        ),
        migrations.AlterModelOptions(
            name='pagos',
            options={'verbose_name_plural': 'Pagos'},
        ),
        migrations.AlterModelOptions(
            name='personas',
            options={'verbose_name_plural': 'Personas'},
        ),
        migrations.AlterModelOptions(
            name='precios',
            options={'verbose_name_plural': 'Precios'},
        ),
        migrations.AlterModelOptions(
            name='recibos',
            options={'verbose_name_plural': 'Recibos'},
        ),
        migrations.AlterModelOptions(
            name='socios',
            options={'verbose_name_plural': 'Socios'},
        ),
        migrations.AlterModelOptions(
            name='socios_cambios',
            options={'verbose_name_plural': 'Historial de cambios'},
        ),
        migrations.RemoveField(
            model_name='personas',
            name='Edad',
        ),
        migrations.RemoveField(
            model_name='socios',
            name='Habilitado',
        ),
        migrations.RemoveField(
            model_name='socios',
            name='cobroEspecial',
        ),
        migrations.RemoveField(
            model_name='socios',
            name='lugarPago',
        ),
        migrations.AlterField(
            model_name='personas',
            name='Cedula',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='Celular',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='Correo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='Direccion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='FechaNacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='PrimerApellido',
            field=models.CharField(max_length=100, verbose_name='Primer apellido'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='PrimerNombre',
            field=models.CharField(max_length=100, verbose_name='Primer nombre'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='SegundoApellido',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo apellido'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='SegundoNombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo nombre'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='Telefono',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='llave',
            field=models.IntegerField(blank=True, null=True, verbose_name='Llave'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='numeroSocio',
            field=models.IntegerField(verbose_name='Número de socio'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='relacionTitular',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Relación titular'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='salud',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Salud'),
        ),
        migrations.AlterField(
            model_name='socios',
            name='activo',
            field=models.IntegerField(blank=True, choices=[(1, 'ALTA'), (0, 'BAJA'), (2, 'PENDIENTE')], null=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='socios',
            name='cedulaTitular',
            field=models.CharField(max_length=11, verbose_name='Cédula del titular'),
        ),
        migrations.AlterField(
            model_name='socios',
            name='comentarios',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='socios',
            name='fechaAlta',
            field=models.DateField(verbose_name='Fecha de alta'),
        ),
        migrations.AlterField(
            model_name='socios',
            name='fechaBaja',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de baja'),
        ),
        migrations.AlterField(
            model_name='socios',
            name='numero',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='socios',
            name='percha',
            field=models.IntegerField(blank=True, null=True, verbose_name='Percha'),
        ),
        migrations.AlterField(
            model_name='socios',
            name='tipo',
            field=models.TextField(verbose_name='Tipo de socio'),
        ),
    ]
