# Generated by Django 4.2.21 on 2026-04-06 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_embarcaciones_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pagos',
        ),
        migrations.DeleteModel(
            name='Precios',
        ),
        migrations.DeleteModel(
            name='Recibos',
        ),
    ]
