# Generated by Django 4.2.21 on 2026-04-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_delete_pagos_delete_precios_delete_recibos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socios',
            options={'verbose_name': 'Socio', 'verbose_name_plural': 'Socios'},
        ),
        migrations.AddField(
            model_name='socios',
            name='fechaAprobacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de aprobación'),
        ),
        migrations.AddField(
            model_name='socios',
            name='fechaSolicitud',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de solicitud'),
        ),
        migrations.AlterField(
            model_name='socios',
            name='activo',
            field=models.IntegerField(blank=True, choices=[(1, 'ALTA'), (0, 'BAJA'), (2, 'PENDIENTE'), (3, 'RECHAZADO')], null=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='socios',
            name='fechaAlta',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de alta'),
        ),
    ]
