# Generated by Django 4.2.21 on 2026-04-09 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_socios_options_socios_fechaaprobacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socios',
            options={'permissions': [('puede_aprobar_socio', 'Puede aprobar socios nuevos'), ('puede_rechazar_socio', 'Puede rechazar solicitudes de socios'), ('puede_dar_baja_socio', 'Puede dar de baja socios activos')], 'verbose_name': 'Socio', 'verbose_name_plural': 'Socios'},
        ),
    ]
