# Generated by Django 4.2.21 on 2026-05-06 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuarios', '0005_alter_socios_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='personas',
            name='estado_habilitacion',
            field=models.CharField(choices=[('NO_HABILITADO', 'No habilitado'), ('HABILITADO', 'Habilitado'), ('SUSPENDIDO', 'Suspendido'), ('REVOCADO', 'Revocado')], default='NO_HABILITADO', editable=False, max_length=20, verbose_name='Estado de habilitación'),
        ),
        migrations.AddField(
            model_name='personas',
            name='fecha_ultimo_calculo_habilitacion',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Último cálculo de habilitación'),
        ),
        migrations.AddField(
            model_name='socios',
            name='tipo_cuota',
            field=models.CharField(choices=[('ANUAL', 'Anual'), ('TEMPORADA', 'Temporada'), ('BECA', 'Beca'), ('EXONERADO', 'Exonerado')], default='ANUAL', max_length=20, verbose_name='Tipo de cuota'),
        ),
        migrations.AddField(
            model_name='socios',
            name='tipo_socio',
            field=models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('FAMILIAR', 'Familiar')], default='INDIVIDUAL', max_length=20, verbose_name='Tipo de socio'),
        ),
        migrations.CreateModel(
            name='AvalComisionDirectiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aval', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_revocacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_revocacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avales_cd', to='usuarios.personas')),
                ('usuario_cd', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avales_otorgados', to=settings.AUTH_USER_MODEL)),
                ('usuario_revocacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avales_revocados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aval de Comisión Directiva',
                'verbose_name_plural': 'Avales de Comisión Directiva',
                'ordering': ['-fecha_aval'],
                'permissions': [('puede_revocar_aval', 'Puede revocar avales de CD')],
            },
        ),
        migrations.CreateModel(
            name='AprobacionProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_socio_momento', models.IntegerField(verbose_name='Número de socio al momento de la aprobación')),
                ('nombre_profesor', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aprobaciones_profesor', to='usuarios.personas')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aprobación de profesor',
                'verbose_name_plural': 'Aprobaciones de profesor',
                'ordering': ['-fecha'],
            },
        ),
    ]
