# Generated by Django 4.2.21 on 2026-05-06 10:00

from django.db import migrations


def migrar_tipos(apps, schema_editor):
    Socios = apps.get_model('usuarios', 'Socios')
    Personas = apps.get_model('usuarios', 'Personas')
    
    for socio in Socios.objects.all():
        tipo_original = socio.tipo.lower().strip() if socio.tipo else ''
        
        if 'individual' in tipo_original:
            socio.tipo_socio = 'INDIVIDUAL'
            socio.tipo_cuota = 'ANUAL'
        elif 'familiar' in tipo_original:
            socio.tipo_socio = 'FAMILIAR'
            socio.tipo_cuota = 'ANUAL'
        elif 'beca' in tipo_original:
            socio.tipo_cuota = 'BECA'
            familiares_count = Personas.objects.filter(numeroSocio=socio.numero).exclude(relacionTitular='TITULAR').count()
            socio.tipo_socio = 'FAMILIAR' if familiares_count > 0 else 'INDIVIDUAL'
        elif 'temporada' in tipo_original:
            socio.tipo_cuota = 'TEMPORADA'
            familiares_count = Personas.objects.filter(numeroSocio=socio.numero).exclude(relacionTitular='TITULAR').count()
            socio.tipo_socio = 'FAMILIAR' if familiares_count > 0 else 'INDIVIDUAL'
        else:
            socio.tipo_socio = 'INDIVIDUAL'
            socio.tipo_cuota = 'ANUAL'
            
        socio.save()

def revertir_migracion(apps, schema_editor):
    Socios = apps.get_model('usuarios', 'Socios')
    for socio in Socios.objects.all():
        if socio.tipo_cuota == 'BECA':
            socio.tipo = 'Beca'
        elif socio.tipo_cuota == 'TEMPORADA':
            socio.tipo = 'Temporada'
        elif socio.tipo_socio == 'FAMILIAR':
            socio.tipo = 'Familiar'
        else:
            socio.tipo = 'Individual'
        socio.save()

class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_personas_estado_habilitacion_and_more'),
    ]

    operations = [
        migrations.RunPython(migrar_tipos, revertir_migracion),
    ]
