# Generated by Django 4.2.21 on 2026-05-06 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_migrar_tipos_socios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socios',
            name='tipo',
        ),
    ]
