# Generated by Django 4.2.21 on 2026-05-06 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_remove_socios_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprobacionprofesor',
            name='numero_socio_momento',
            field=models.IntegerField(blank=True, null=True, verbose_name='Número de socio al momento de la aprobación'),
        ),
    ]
